// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: events/eventmessages/entryCredit.proto

package eventmessages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryCreditBlock struct {
	Header               *EntryCreditBlockHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Entries              []*EntryCreditBlockEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EntryCreditBlock) Reset()         { *m = EntryCreditBlock{} }
func (m *EntryCreditBlock) String() string { return proto.CompactTextString(m) }
func (*EntryCreditBlock) ProtoMessage()    {}
func (*EntryCreditBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e5d242581df78b, []int{0}
}
func (m *EntryCreditBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EntryCreditBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EntryCreditBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EntryCreditBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryCreditBlock.Merge(m, src)
}
func (m *EntryCreditBlock) XXX_Size() int {
	return m.Size()
}
func (m *EntryCreditBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryCreditBlock.DiscardUnknown(m)
}

var xxx_messageInfo_EntryCreditBlock proto.InternalMessageInfo

func (m *EntryCreditBlock) GetHeader() *EntryCreditBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EntryCreditBlock) GetEntries() []*EntryCreditBlockEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type EntryCreditBlockHeader struct {
	BodyHash             *Hash    `protobuf:"bytes,1,opt,name=bodyHash,proto3" json:"bodyHash,omitempty"`
	PreviousHeaderHash   *Hash    `protobuf:"bytes,2,opt,name=previousHeaderHash,proto3" json:"previousHeaderHash,omitempty"`
	PreviousFullHash     *Hash    `protobuf:"bytes,3,opt,name=previousFullHash,proto3" json:"previousFullHash,omitempty"`
	BlockHeight          uint32   `protobuf:"varint,4,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	HeaderExpansionArea  []byte   `protobuf:"bytes,5,opt,name=HeaderExpansionArea,proto3" json:"HeaderExpansionArea,omitempty"`
	ObjectCount          uint64   `protobuf:"varint,6,opt,name=objectCount,proto3" json:"objectCount,omitempty"`
	BodySize             uint64   `protobuf:"varint,7,opt,name=bodySize,proto3" json:"bodySize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryCreditBlockHeader) Reset()         { *m = EntryCreditBlockHeader{} }
func (m *EntryCreditBlockHeader) String() string { return proto.CompactTextString(m) }
func (*EntryCreditBlockHeader) ProtoMessage()    {}
func (*EntryCreditBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e5d242581df78b, []int{1}
}
func (m *EntryCreditBlockHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EntryCreditBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EntryCreditBlockHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EntryCreditBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryCreditBlockHeader.Merge(m, src)
}
func (m *EntryCreditBlockHeader) XXX_Size() int {
	return m.Size()
}
func (m *EntryCreditBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryCreditBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_EntryCreditBlockHeader proto.InternalMessageInfo

func (m *EntryCreditBlockHeader) GetBodyHash() *Hash {
	if m != nil {
		return m.BodyHash
	}
	return nil
}

func (m *EntryCreditBlockHeader) GetPreviousHeaderHash() *Hash {
	if m != nil {
		return m.PreviousHeaderHash
	}
	return nil
}

func (m *EntryCreditBlockHeader) GetPreviousFullHash() *Hash {
	if m != nil {
		return m.PreviousFullHash
	}
	return nil
}

func (m *EntryCreditBlockHeader) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *EntryCreditBlockHeader) GetHeaderExpansionArea() []byte {
	if m != nil {
		return m.HeaderExpansionArea
	}
	return nil
}

func (m *EntryCreditBlockHeader) GetObjectCount() uint64 {
	if m != nil {
		return m.ObjectCount
	}
	return 0
}

func (m *EntryCreditBlockHeader) GetBodySize() uint64 {
	if m != nil {
		return m.BodySize
	}
	return 0
}

type EntryCreditBlockEntry struct {
	// Types that are valid to be assigned to Value:
	//	*EntryCreditBlockEntry_CommitChain
	//	*EntryCreditBlockEntry_CommitEntry
	//	*EntryCreditBlockEntry_IncreaseBalance
	//	*EntryCreditBlockEntry_MinuteNumber
	//	*EntryCreditBlockEntry_ServerIndexNumber
	Value                isEntryCreditBlockEntry_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *EntryCreditBlockEntry) Reset()         { *m = EntryCreditBlockEntry{} }
func (m *EntryCreditBlockEntry) String() string { return proto.CompactTextString(m) }
func (*EntryCreditBlockEntry) ProtoMessage()    {}
func (*EntryCreditBlockEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e5d242581df78b, []int{2}
}
func (m *EntryCreditBlockEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EntryCreditBlockEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EntryCreditBlockEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EntryCreditBlockEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryCreditBlockEntry.Merge(m, src)
}
func (m *EntryCreditBlockEntry) XXX_Size() int {
	return m.Size()
}
func (m *EntryCreditBlockEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryCreditBlockEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EntryCreditBlockEntry proto.InternalMessageInfo

type isEntryCreditBlockEntry_Value interface {
	isEntryCreditBlockEntry_Value()
	MarshalTo([]byte) (int, error)
	Size() int
}

type EntryCreditBlockEntry_CommitChain struct {
	CommitChain *ChainRegistration `protobuf:"bytes,1,opt,name=commitChain,proto3,oneof"`
}
type EntryCreditBlockEntry_CommitEntry struct {
	CommitEntry *EntryRegistration `protobuf:"bytes,2,opt,name=commitEntry,proto3,oneof"`
}
type EntryCreditBlockEntry_IncreaseBalance struct {
	IncreaseBalance *IncreaseBalance `protobuf:"bytes,3,opt,name=increaseBalance,proto3,oneof"`
}
type EntryCreditBlockEntry_MinuteNumber struct {
	MinuteNumber uint32 `protobuf:"varint,4,opt,name=minuteNumber,proto3,oneof"`
}
type EntryCreditBlockEntry_ServerIndexNumber struct {
	ServerIndexNumber uint32 `protobuf:"varint,5,opt,name=serverIndexNumber,proto3,oneof"`
}

func (*EntryCreditBlockEntry_CommitChain) isEntryCreditBlockEntry_Value()       {}
func (*EntryCreditBlockEntry_CommitEntry) isEntryCreditBlockEntry_Value()       {}
func (*EntryCreditBlockEntry_IncreaseBalance) isEntryCreditBlockEntry_Value()   {}
func (*EntryCreditBlockEntry_MinuteNumber) isEntryCreditBlockEntry_Value()      {}
func (*EntryCreditBlockEntry_ServerIndexNumber) isEntryCreditBlockEntry_Value() {}

func (m *EntryCreditBlockEntry) GetValue() isEntryCreditBlockEntry_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *EntryCreditBlockEntry) GetCommitChain() *ChainRegistration {
	if x, ok := m.GetValue().(*EntryCreditBlockEntry_CommitChain); ok {
		return x.CommitChain
	}
	return nil
}

func (m *EntryCreditBlockEntry) GetCommitEntry() *EntryRegistration {
	if x, ok := m.GetValue().(*EntryCreditBlockEntry_CommitEntry); ok {
		return x.CommitEntry
	}
	return nil
}

func (m *EntryCreditBlockEntry) GetIncreaseBalance() *IncreaseBalance {
	if x, ok := m.GetValue().(*EntryCreditBlockEntry_IncreaseBalance); ok {
		return x.IncreaseBalance
	}
	return nil
}

func (m *EntryCreditBlockEntry) GetMinuteNumber() uint32 {
	if x, ok := m.GetValue().(*EntryCreditBlockEntry_MinuteNumber); ok {
		return x.MinuteNumber
	}
	return 0
}

func (m *EntryCreditBlockEntry) GetServerIndexNumber() uint32 {
	if x, ok := m.GetValue().(*EntryCreditBlockEntry_ServerIndexNumber); ok {
		return x.ServerIndexNumber
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EntryCreditBlockEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EntryCreditBlockEntry_OneofMarshaler, _EntryCreditBlockEntry_OneofUnmarshaler, _EntryCreditBlockEntry_OneofSizer, []interface{}{
		(*EntryCreditBlockEntry_CommitChain)(nil),
		(*EntryCreditBlockEntry_CommitEntry)(nil),
		(*EntryCreditBlockEntry_IncreaseBalance)(nil),
		(*EntryCreditBlockEntry_MinuteNumber)(nil),
		(*EntryCreditBlockEntry_ServerIndexNumber)(nil),
	}
}

func _EntryCreditBlockEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EntryCreditBlockEntry)
	// value
	switch x := m.Value.(type) {
	case *EntryCreditBlockEntry_CommitChain:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CommitChain); err != nil {
			return err
		}
	case *EntryCreditBlockEntry_CommitEntry:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CommitEntry); err != nil {
			return err
		}
	case *EntryCreditBlockEntry_IncreaseBalance:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IncreaseBalance); err != nil {
			return err
		}
	case *EntryCreditBlockEntry_MinuteNumber:
		_ = b.EncodeVarint(4<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.MinuteNumber))
	case *EntryCreditBlockEntry_ServerIndexNumber:
		_ = b.EncodeVarint(5<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.ServerIndexNumber))
	case nil:
	default:
		return fmt.Errorf("EntryCreditBlockEntry.Value has unexpected type %T", x)
	}
	return nil
}

func _EntryCreditBlockEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EntryCreditBlockEntry)
	switch tag {
	case 1: // value.commitChain
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ChainRegistration)
		err := b.DecodeMessage(msg)
		m.Value = &EntryCreditBlockEntry_CommitChain{msg}
		return true, err
	case 2: // value.commitEntry
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EntryRegistration)
		err := b.DecodeMessage(msg)
		m.Value = &EntryCreditBlockEntry_CommitEntry{msg}
		return true, err
	case 3: // value.increaseBalance
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IncreaseBalance)
		err := b.DecodeMessage(msg)
		m.Value = &EntryCreditBlockEntry_IncreaseBalance{msg}
		return true, err
	case 4: // value.minuteNumber
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EntryCreditBlockEntry_MinuteNumber{uint32(x)}
		return true, err
	case 5: // value.serverIndexNumber
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &EntryCreditBlockEntry_ServerIndexNumber{uint32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _EntryCreditBlockEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EntryCreditBlockEntry)
	// value
	switch x := m.Value.(type) {
	case *EntryCreditBlockEntry_CommitChain:
		s := proto.Size(x.CommitChain)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EntryCreditBlockEntry_CommitEntry:
		s := proto.Size(x.CommitEntry)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EntryCreditBlockEntry_IncreaseBalance:
		s := proto.Size(x.IncreaseBalance)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EntryCreditBlockEntry_MinuteNumber:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.MinuteNumber))
	case *EntryCreditBlockEntry_ServerIndexNumber:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.ServerIndexNumber))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IncreaseBalance struct {
	EcPubKey             []byte   `protobuf:"bytes,1,opt,name=ecPubKey,proto3" json:"ecPubKey,omitempty"`
	TxID                 *Hash    `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	Index                uint64   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	EcAmount             uint64   `protobuf:"varint,4,opt,name=ecAmount,proto3" json:"ecAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseBalance) Reset()         { *m = IncreaseBalance{} }
func (m *IncreaseBalance) String() string { return proto.CompactTextString(m) }
func (*IncreaseBalance) ProtoMessage()    {}
func (*IncreaseBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_80e5d242581df78b, []int{3}
}
func (m *IncreaseBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IncreaseBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IncreaseBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IncreaseBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseBalance.Merge(m, src)
}
func (m *IncreaseBalance) XXX_Size() int {
	return m.Size()
}
func (m *IncreaseBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseBalance.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseBalance proto.InternalMessageInfo

func (m *IncreaseBalance) GetEcPubKey() []byte {
	if m != nil {
		return m.EcPubKey
	}
	return nil
}

func (m *IncreaseBalance) GetTxID() *Hash {
	if m != nil {
		return m.TxID
	}
	return nil
}

func (m *IncreaseBalance) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *IncreaseBalance) GetEcAmount() uint64 {
	if m != nil {
		return m.EcAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*EntryCreditBlock)(nil), "eventmessages.EntryCreditBlock")
	proto.RegisterType((*EntryCreditBlockHeader)(nil), "eventmessages.EntryCreditBlockHeader")
	proto.RegisterType((*EntryCreditBlockEntry)(nil), "eventmessages.EntryCreditBlockEntry")
	proto.RegisterType((*IncreaseBalance)(nil), "eventmessages.IncreaseBalance")
}

func init() {
	proto.RegisterFile("events/eventmessages/entryCredit.proto", fileDescriptor_80e5d242581df78b)
}

var fileDescriptor_80e5d242581df78b = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xce, 0xa6, 0xf9, 0x41, 0x93, 0x54, 0x2d, 0x2e, 0xa0, 0x55, 0x0f, 0xd1, 0x2a, 0x2a, 0x34,
	0xa7, 0x04, 0x95, 0x33, 0xa0, 0x24, 0x2d, 0x4a, 0x40, 0x42, 0xc8, 0x70, 0xe2, 0xe6, 0xdd, 0x0c,
	0x89, 0x61, 0xd7, 0x8e, 0x6c, 0x6f, 0x94, 0xf0, 0x04, 0x5c, 0xb9, 0xf1, 0x48, 0x9c, 0x10, 0x8f,
	0x00, 0xe1, 0x45, 0x50, 0xbc, 0x9b, 0x34, 0xbb, 0xdd, 0xc2, 0xc9, 0x9a, 0x99, 0xef, 0xfb, 0x66,
	0x3c, 0x9f, 0x65, 0x78, 0x84, 0x0b, 0x14, 0x46, 0xf7, 0xec, 0x11, 0xa1, 0xd6, 0x6c, 0x8a, 0xba,
	0x87, 0xc2, 0xa8, 0xd5, 0x50, 0xe1, 0x84, 0x9b, 0xee, 0x5c, 0x49, 0x23, 0xc9, 0x61, 0x06, 0x70,
	0x7a, 0x5e, 0x48, 0x9b, 0xa2, 0x40, 0xc5, 0xc2, 0x77, 0xab, 0x39, 0xea, 0x84, 0xd7, 0xfe, 0xea,
	0xc0, 0xf1, 0xd5, 0xb5, 0xda, 0x20, 0x94, 0xc1, 0x27, 0xf2, 0x14, 0x6a, 0x33, 0x64, 0x13, 0x54,
	0xae, 0xe3, 0x39, 0x9d, 0xc6, 0xc5, 0xc3, 0x6e, 0x46, 0xa7, 0x9b, 0x27, 0x8c, 0x2c, 0x98, 0xa6,
	0x24, 0xf2, 0x0c, 0xea, 0x9b, 0x01, 0x39, 0x6a, 0xb7, 0xec, 0x1d, 0x74, 0x1a, 0x17, 0x67, 0xff,
	0xe1, 0xdb, 0x98, 0x6e, 0x49, 0xed, 0xdf, 0x65, 0x78, 0x50, 0xdc, 0x82, 0xf4, 0xe0, 0x8e, 0x2f,
	0x27, 0xab, 0x11, 0xd3, 0xb3, 0x74, 0xb6, 0x93, 0x9c, 0xf6, 0xa6, 0x44, 0x77, 0x20, 0x32, 0x04,
	0x32, 0x57, 0xb8, 0xe0, 0x32, 0xd6, 0x89, 0x84, 0xa5, 0x96, 0x6f, 0xa7, 0x16, 0xc0, 0xc9, 0x73,
	0x38, 0xde, 0x66, 0x5f, 0xc4, 0x61, 0x68, 0x25, 0x0e, 0x6e, 0x97, 0xb8, 0x01, 0x26, 0x1e, 0x34,
	0xfc, 0xe4, 0x16, 0x7c, 0x3a, 0x33, 0x6e, 0xc5, 0x73, 0x3a, 0x87, 0x74, 0x3f, 0x45, 0x1e, 0xc3,
	0x49, 0xd2, 0xf0, 0x6a, 0x39, 0x67, 0x42, 0x73, 0x29, 0xfa, 0x0a, 0x99, 0x5b, 0xf5, 0x9c, 0x4e,
	0x93, 0x16, 0x95, 0x36, 0x9a, 0xd2, 0xff, 0x88, 0x81, 0x19, 0xca, 0x58, 0x18, 0xb7, 0xe6, 0x39,
	0x9d, 0x0a, 0xdd, 0x4f, 0x91, 0xd3, 0x64, 0x59, 0x6f, 0xf9, 0x67, 0x74, 0xeb, 0xb6, 0xbc, 0x8b,
	0xdb, 0x3f, 0xca, 0x70, 0xbf, 0xd0, 0x06, 0x72, 0x09, 0x8d, 0x40, 0x46, 0x11, 0x37, 0xc3, 0x19,
	0xe3, 0x22, 0xdd, 0xb2, 0x97, 0xbb, 0xa7, 0xad, 0x51, 0x9c, 0x72, 0x6d, 0x14, 0x33, 0x5c, 0x8a,
	0x51, 0x89, 0xee, 0xd3, 0xae, 0x55, 0xac, 0x68, 0xba, 0x70, 0xaf, 0xe8, 0x1d, 0x14, 0xab, 0x24,
	0xb3, 0xbc, 0x84, 0x23, 0x2e, 0x02, 0x85, 0x4c, 0xe3, 0x80, 0x85, 0x4c, 0x04, 0x98, 0xee, 0xbd,
	0x95, 0x53, 0x1a, 0x67, 0x51, 0xa3, 0x12, 0xcd, 0x13, 0xc9, 0x19, 0x34, 0x23, 0x2e, 0x62, 0x83,
	0xaf, 0xe3, 0xc8, 0x47, 0x95, 0x98, 0x30, 0x2a, 0xd1, 0x4c, 0x96, 0x74, 0xe1, 0xae, 0x46, 0xb5,
	0x40, 0x35, 0x16, 0x13, 0x5c, 0xa6, 0xd0, 0x6a, 0x0a, 0xbd, 0x59, 0x1a, 0xd4, 0xa1, 0xba, 0x60,
	0x61, 0x8c, 0xed, 0x2f, 0x0e, 0x1c, 0xe5, 0xa6, 0xd8, 0x18, 0x80, 0xc1, 0x9b, 0xd8, 0x7f, 0x85,
	0x2b, 0xbb, 0xc7, 0x26, 0xdd, 0xc5, 0xe4, 0x1c, 0x2a, 0x66, 0x39, 0xbe, 0xfc, 0xd7, 0x53, 0xb4,
	0x00, 0x72, 0x0f, 0xaa, 0x7c, 0xd3, 0xd0, 0xde, 0xbc, 0x42, 0x93, 0x20, 0x91, 0xee, 0x47, 0xd6,
	0xfa, 0x4a, 0xe2, 0xed, 0x36, 0x1e, 0xf4, 0xbf, 0xaf, 0x5b, 0xce, 0xcf, 0x75, 0xcb, 0xf9, 0xb5,
	0x6e, 0x39, 0xdf, 0xfe, 0xb4, 0x4a, 0xe0, 0x05, 0x32, 0xea, 0x7e, 0x60, 0x81, 0xd9, 0x1d, 0x93,
	0x6c, 0xc3, 0xf7, 0xd9, 0xff, 0xc3, 0xaf, 0xd9, 0xdf, 0xe1, 0xc9, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf0, 0x97, 0x67, 0xba, 0x7f, 0x04, 0x00, 0x00,
}

func (m *EntryCreditBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EntryCreditBlock) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.Header.Size()))
		n1, err1 := m.Header.MarshalTo(dAtA[i:])
		if err1 != nil {
			return 0, err1
		}
		i += n1
	}
	if len(m.Entries) > 0 {
		for _, msg := range m.Entries {
			dAtA[i] = 0x12
			i++
			i = encodeVarintEntryCredit(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EntryCreditBlockHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EntryCreditBlockHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.BodyHash != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.BodyHash.Size()))
		n2, err2 := m.BodyHash.MarshalTo(dAtA[i:])
		if err2 != nil {
			return 0, err2
		}
		i += n2
	}
	if m.PreviousHeaderHash != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.PreviousHeaderHash.Size()))
		n3, err3 := m.PreviousHeaderHash.MarshalTo(dAtA[i:])
		if err3 != nil {
			return 0, err3
		}
		i += n3
	}
	if m.PreviousFullHash != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.PreviousFullHash.Size()))
		n4, err4 := m.PreviousFullHash.MarshalTo(dAtA[i:])
		if err4 != nil {
			return 0, err4
		}
		i += n4
	}
	if m.BlockHeight != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.BlockHeight))
	}
	if len(m.HeaderExpansionArea) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(len(m.HeaderExpansionArea)))
		i += copy(dAtA[i:], m.HeaderExpansionArea)
	}
	if m.ObjectCount != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.ObjectCount))
	}
	if m.BodySize != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.BodySize))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EntryCreditBlockEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EntryCreditBlockEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Value != nil {
		nn5, err5 := m.Value.MarshalTo(dAtA[i:])
		if err5 != nil {
			return 0, err5
		}
		i += nn5
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EntryCreditBlockEntry_CommitChain) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CommitChain != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.CommitChain.Size()))
		n6, err6 := m.CommitChain.MarshalTo(dAtA[i:])
		if err6 != nil {
			return 0, err6
		}
		i += n6
	}
	return i, nil
}
func (m *EntryCreditBlockEntry_CommitEntry) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CommitEntry != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.CommitEntry.Size()))
		n7, err7 := m.CommitEntry.MarshalTo(dAtA[i:])
		if err7 != nil {
			return 0, err7
		}
		i += n7
	}
	return i, nil
}
func (m *EntryCreditBlockEntry_IncreaseBalance) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.IncreaseBalance != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.IncreaseBalance.Size()))
		n8, err8 := m.IncreaseBalance.MarshalTo(dAtA[i:])
		if err8 != nil {
			return 0, err8
		}
		i += n8
	}
	return i, nil
}
func (m *EntryCreditBlockEntry_MinuteNumber) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	dAtA[i] = 0x20
	i++
	i = encodeVarintEntryCredit(dAtA, i, uint64(m.MinuteNumber))
	return i, nil
}
func (m *EntryCreditBlockEntry_ServerIndexNumber) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	dAtA[i] = 0x28
	i++
	i = encodeVarintEntryCredit(dAtA, i, uint64(m.ServerIndexNumber))
	return i, nil
}
func (m *IncreaseBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IncreaseBalance) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.EcPubKey) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(len(m.EcPubKey)))
		i += copy(dAtA[i:], m.EcPubKey)
	}
	if m.TxID != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.TxID.Size()))
		n9, err9 := m.TxID.MarshalTo(dAtA[i:])
		if err9 != nil {
			return 0, err9
		}
		i += n9
	}
	if m.Index != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.Index))
	}
	if m.EcAmount != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintEntryCredit(dAtA, i, uint64(m.EcAmount))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintEntryCredit(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *EntryCreditBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovEntryCredit(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EntryCreditBlockHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BodyHash != nil {
		l = m.BodyHash.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	if m.PreviousHeaderHash != nil {
		l = m.PreviousHeaderHash.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	if m.PreviousFullHash != nil {
		l = m.PreviousFullHash.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovEntryCredit(uint64(m.BlockHeight))
	}
	l = len(m.HeaderExpansionArea)
	if l > 0 {
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	if m.ObjectCount != 0 {
		n += 1 + sovEntryCredit(uint64(m.ObjectCount))
	}
	if m.BodySize != 0 {
		n += 1 + sovEntryCredit(uint64(m.BodySize))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EntryCreditBlockEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value != nil {
		n += m.Value.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EntryCreditBlockEntry_CommitChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommitChain != nil {
		l = m.CommitChain.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	return n
}
func (m *EntryCreditBlockEntry_CommitEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommitEntry != nil {
		l = m.CommitEntry.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	return n
}
func (m *EntryCreditBlockEntry_IncreaseBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IncreaseBalance != nil {
		l = m.IncreaseBalance.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	return n
}
func (m *EntryCreditBlockEntry_MinuteNumber) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovEntryCredit(uint64(m.MinuteNumber))
	return n
}
func (m *EntryCreditBlockEntry_ServerIndexNumber) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovEntryCredit(uint64(m.ServerIndexNumber))
	return n
}
func (m *IncreaseBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EcPubKey)
	if l > 0 {
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	if m.TxID != nil {
		l = m.TxID.Size()
		n += 1 + l + sovEntryCredit(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovEntryCredit(uint64(m.Index))
	}
	if m.EcAmount != 0 {
		n += 1 + sovEntryCredit(uint64(m.EcAmount))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEntryCredit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEntryCredit(x uint64) (n int) {
	return sovEntryCredit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EntryCreditBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntryCredit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EntryCreditBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EntryCreditBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &EntryCreditBlockHeader{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &EntryCreditBlockEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntryCredit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EntryCreditBlockHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntryCredit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EntryCreditBlockHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EntryCreditBlockHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyHash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BodyHash == nil {
				m.BodyHash = &Hash{}
			}
			if err := m.BodyHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousHeaderHash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PreviousHeaderHash == nil {
				m.PreviousHeaderHash = &Hash{}
			}
			if err := m.PreviousHeaderHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousFullHash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PreviousFullHash == nil {
				m.PreviousFullHash = &Hash{}
			}
			if err := m.PreviousFullHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeaderExpansionArea", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeaderExpansionArea = append(m.HeaderExpansionArea[:0], dAtA[iNdEx:postIndex]...)
			if m.HeaderExpansionArea == nil {
				m.HeaderExpansionArea = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectCount", wireType)
			}
			m.ObjectCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObjectCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodySize", wireType)
			}
			m.BodySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BodySize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEntryCredit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EntryCreditBlockEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntryCredit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EntryCreditBlockEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EntryCreditBlockEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitChain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ChainRegistration{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Value = &EntryCreditBlockEntry_CommitChain{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitEntry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &EntryRegistration{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Value = &EntryCreditBlockEntry_CommitEntry{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncreaseBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IncreaseBalance{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Value = &EntryCreditBlockEntry_IncreaseBalance{v}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinuteNumber", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Value = &EntryCreditBlockEntry_MinuteNumber{v}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerIndexNumber", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Value = &EntryCreditBlockEntry_ServerIndexNumber{v}
		default:
			iNdEx = preIndex
			skippy, err := skipEntryCredit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IncreaseBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntryCredit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IncreaseBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IncreaseBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EcPubKey = append(m.EcPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.EcPubKey == nil {
				m.EcPubKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntryCredit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TxID == nil {
				m.TxID = &Hash{}
			}
			if err := m.TxID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcAmount", wireType)
			}
			m.EcAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EcAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEntryCredit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEntryCredit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEntryCredit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEntryCredit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntryCredit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEntryCredit
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthEntryCredit
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEntryCredit
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEntryCredit(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthEntryCredit
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEntryCredit = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEntryCredit   = fmt.Errorf("proto: integer overflow")
)
